#!/usr/bin/perl -T
#
# output_rate_table
#
# gives out the Rate=f(t) probe output for the singe traffic used here
#
#$inputfilename = "./output/IP_windowedEndToEndIncomingBitThroughput_Log.log.dat";
#$inputfilename = "./output/ip.endToEnd.window.incoming.bitThroughput_Log.log.dat";

$outputDir = "./output"; # default
$outputDirFile = "./outputDir.junk"; # see constanzeTestsGlue.py
if ((-r $outputDirFile) && (open(ODF, $outputDirFile))) {
  #chop($outputDir = <ODF>);
  $outputDir = <ODF>;
  close(ODF);
}
#if (! -d $outputDir) { die "cannot access outputDir=\"$outputDir\""; }
if (! -d $outputDir) { print stderr "cannot access outputDir=\"$outputDir\"\n"; }
# ^ currenty $outputDir returns "output" always, although it is elsewhere.
# workaround:
$inputfilename = "$outputDir/ip.endToEnd.window.incoming.bitThroughput_Log.log.dat";
if ((! -d $outputDir) || (! -r $inputfilename)) {
  if (-d "output_dbg_constanzeTestsGlue.py") {
	$outputDir="output_dbg_constanzeTestsGlue.py";
  } elsif (-d "output_opt_constanzeTestsGlue.py") {
	$outputDir="output_opt_constanzeTestsGlue.py";
  }
}
$inputfilename = "$outputDir/ip.endToEnd.window.incoming.bitThroughput_Log.log.dat";
open(IF,$inputfilename) || die "cannot open input file \"$inputfilename\"";
#print stderr "processing $inputfilename\n";

while($line=<IF>) {
  if ($line =~ /^\s*#/) {
    # comment line
  } else {
    my($t,$r)=split(/\s+/,$line);
    if ($t != $last_t) {
      # output of first Probe
    } else {
      # output of second Probe
      print "$t\t$r\n";
   }
    $last_t=$t;
  }
}
